version: "3"
services:
  api:
    environment:
      DATABASE_HOST: postgres
      PORT: 8080
    #    build service based from Dockerfile
    build: .
    command: npm run start
    depends_on:
      - postgres
#    container's port is exposed and mapped to our machines localhost:8080
    ports:
      - "8080:8080"
  postgres:
    image: postgres:11.1-alpine
    restart: always
#    overriding environment vars to create user, password and database
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: qwerty1
      POSTGRES_DB: photoalbumdb
#    container's port is exposed and mapped to our machines localhost:5431
    ports:
      - 5431:5432
